from backend.schemas.mirror import OAuthCredentialOut, OAuthCredentialUpsertRequest


OAuthProviderOut = OAuthCredentialOut
OAuthProviderCreate = OAuthCredentialUpsertRequest
OAuthProviderUpdate = OAuthCredentialUpsertRequest
