name = "smart-mirror-d1-sync"
main = "src/index.ts"
compatibility_date = "2026-04-22"

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "MIRROR_DB"
database_name = "MIRROR_DB"
database_id = "25103f8c-8cf6-4c32-9f24-5feaeb494360"
